### PR TITLE
Update appmetrics-dash and appmetrics-prometheus versions

### PR DESCRIPTION
**Pull request by sjanuary**
appmetrics-dash and appmetrics-prometheus have just had major version increments.  This PR pulls the latest versions into generated applications.

### CODE REVIEW

**Comment by Aerex** [comment]
@sjanuary Would you mind rebasing your commit to include the prefix `fix: `. This way the patch will show in the changelog for the next release.

**Comment by sjanuary** [comment]
@Aerex - done

**Comment by sjanuary** [comment]
@Aerex - do you have an approximate timescale for the next release?  Thanks

**Comment by Aerex** [comment]
@sjanuary I would say sometime during the week

**Comment by sjanuary** [comment]
great, thanks

**Comment by tobespc** [comment]
@Aerex Can this be merged yet ?

**Comment by tobespc** [comment]
nope

**Pull request merged**
