### PR TITLE
fix(docker): Switch the base image to node:8 from ibmnode

### PR DESCRIPTION
**Pull request by sjc-code**

### CODE REVIEW

**Comment by sjc-code** [comment]
This has a corresponding equivalent change in generator-ibm-cloud-enablement
I have no idea what determines which of the Dockerfile(-tools) templates is actually used

**Comment by Aerex** [comment]
Resolved in [PR 270](https://github.com/ibm-developer/generator-ibm-cloud-enablement/pull/270)

**Comment by sjc-code** [comment]
@aerex Why does PR 270 (for generator-ibm-cloud-enablement) resolve this PR (for core-node-express) ?
Are you saying that the Dockerfile template in core-node-express is never actually used... so there's no need to update it... so it should actually be removed ?

**Comment by Aerex** [comment]
@sjc-code Not exactly. At the inception of cloud-enablement, core-node-express produced the cloud artifacts such as Dockerfile and Dockerfile-tools. When cloud-enablement was created we made it so that if there are any files that already existed do not override it. In most cases, core-node-express is run before cloud-enablement. Thus, if you made any changes in cloud-enablement it wil not show up in generation because core-node-express will have already created it during runtime.

To remove any  confusion, I have removed the artifacts to  cloud-enablement to core-node express.

**Comment by sjc-code** [comment]
@aerex 
> To remove any confusion, I have removed the artifacts to cloud-enablement to core-node express.
Sorry, I don't understand this sentence.

And if core-node-express "wins" when it runs first, then we still need to update the Dockerfile(-tools) template in core-node-express (which is this PR).... so still don't understand why it's closed.

**Pull request closed without merging**
